In [45]:
import pandas as pd

In [46]:
csv_file ="liste_incendies_ du_12_08_2022.csv"
df = pd.read_csv(csv_file, skiprows=2, sep=";") # store csv data in a dataframe, by skipping both first rows

In [47]:
df.set_index("Numéro")

,Année,Type de feu,Département,Code INSEE,Commune,Lieu-dit,Code du carreau DFCI,Alerte,Origine de l'alerte,Surface parcourue (m2)
Numéro,,,,,,,,,,
5307,2022,0,04,04152,Pierrevert,avenue de la milière,KD66H7,2022-08-11 05:42:00,3.0,50
5277,2022,0,06,06074,Lantosque,saint colomban,MD08A8,2022-08-10 15:02:00,3.0,40
5275,2022,0,30,30189,Nîmes,NaN,HD46K83,2022-08-09 19:25:00,NaN,500
5194,2022,0,2B,2B123,Ghisonaccia,foret de Pinia,NB88F8,2022-08-09 11:13:00,NaN,400
5268,2022,0,30,30243,Saint-Christol-lès-Alès,NaN,HD28K92,2022-08-09 06:53:00,NaN,5000
...,...,...,...,...,...,...,...,...,...,...
1380,2000,0,06,06010,Bar-sur-Loup (Le),LE TERROY,LD66H35,2000-01-03 16:00:00,6.0,2000
928,2000,0,06,06147,Tourrette-Levens,SCIALVIERA,LD86K92,2000-01-02 13:50:00,3.0,100
2067,2000,0,2A,2A348,Vico,LA PIEVE,NC20H33,2000-01-02 12:15:00,3.0,80
506,2000,0,2B,2B303,San-Giuliano,NaN,NC82G25,2000-01-01 17:41:00,3.0,20000
2644,2000,0,48,48001,Albaret-le-Comtal,test (a supprimer),KD22A2,2000-01-01 01:01:00,NaN,1000

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42482 entries, 0 to 42481
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Année                   42482 non-null  int64
 1   Numéro                  42482 non-null  int64
 2   Type de feu             42482 non-null  int64
 3   Département             42482 non-null  object
 4   Code INSEE              42482 non-null  object
 5   Commune                 42482 non-null  object
 6   Lieu-dit                33371 non-null  object
 7   Code du carreau DFCI    42482 non-null  object
 8   Alerte                  42482 non-null  object
 9   Origine de l'alerte     32877 non-null  float64
 10  Surface parcourue (m2)  42482 non-null  int64
dtypes: float64(1), int64(4), object(6)
memory usage: 3.6+ MB

In [49]:
df[["Date", 'Time']] = df["Alerte"].str.split(' ', expand=True)
df["Date"] = df['Date'].astype('datetime64[ns]')
df["Time"] = pd.to_datetime(df["Time"], format='%H:%M:%S').dt.time

In [57]:
df

,Année,Numéro,Type de feu,Département,Code INSEE,Commune,Lieu-dit,Code du carreau DFCI,Alerte,Origine de l'alerte,Surface parcourue (m2),Date,Time
0,2022,5307,0,04,04152,Pierrevert,avenue de la milière,KD66H7,2022-08-11 05:42:00,3.0,50,2022-08-11,05:42:00
1,2022,5277,0,06,06074,Lantosque,saint colomban,MD08A8,2022-08-10 15:02:00,3.0,40,2022-08-10,15:02:00
2,2022,5275,0,30,30189,Nîmes,NaN,HD46K83,2022-08-09 19:25:00,NaN,500,2022-08-09,19:25:00
3,2022,5194,0,2B,2B123,Ghisonaccia,foret de Pinia,NB88F8,2022-08-09 11:13:00,NaN,400,2022-08-09,11:13:00
4,2022,5268,0,30,30243,Saint-Christol-lès-Alès,NaN,HD28K92,2022-08-09 06:53:00,NaN,5000,2022-08-09,06:53:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42477,2000,1380,0,06,06010,Bar-sur-Loup (Le),LE TERROY,LD66H35,2000-01-03 16:00:00,6.0,2000,2000-01-03,16:00:00
42478,2000,928,0,06,06147,Tourrette-Levens,SCIALVIERA,LD86K92,2000-01-02 13:50:00,3.0,100,2000-01-02,13:50:00
42479,2000,2067,0,2A,2A348,Vico,LA PIEVE,NC20H33,2000-01-02 12:15:00,3.0,80,2000-01-02,12:15:00
42480,2000,506,0,2B,2B303,San-Giuliano,NaN,NC82G25,2000-01-01 17:41:00,3.0,20000,2000-01-01,17:41:00
42481,2000,2644,0,48,48001,Albaret-le-Comtal,test (a supprimer),KD22A2,2000-01-01 01:01:00,NaN,1000,2000-01-01,01:01:00

,Année,Numéro,Type de feu,Département,Code INSEE,Commune,Lieu-dit,Code du carreau DFCI,Alerte,Origine de l'alerte,Surface parcourue (m2),Date,Time
0,2022,5307,0,04,04152,Pierrevert,avenue de la milière,KD66H7,2022-08-11 05:42:00,3.0,50,2022-08-11,05:42:00
1,2022,5277,0,06,06074,Lantosque,saint colomban,MD08A8,2022-08-10 15:02:00,3.0,40,2022-08-10,15:02:00
2,2022,5275,0,30,30189,Nîmes,NaN,HD46K83,2022-08-09 19:25:00,NaN,500,2022-08-09,19:25:00
3,2022,5194,0,2B,2B123,Ghisonaccia,foret de Pinia,NB88F8,2022-08-09 11:13:00,NaN,400,2022-08-09,11:13:00
4,2022,5268,0,30,30243,Saint-Christol-lès-Alès,NaN,HD28K92,2022-08-09 06:53:00,NaN,5000,2022-08-09,06:53:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42477,2000,1380,0,06,06010,Bar-sur-Loup (Le),LE TERROY,LD66H35,2000-01-03 16:00:00,6.0,2000,2000-01-03,16:00:00
42478,2000,928,0,06,06147,Tourrette-Levens,SCIALVIERA,LD86K92,2000-01-02 13:50:00,3.0,100,2000-01-02,13:50:00
42479,2000,2067,0,2A,2A348,Vico,LA PIEVE,NC20H33,2000-01-02 12:15:00,3.0,80,2000-01-02,12:15:00
42480,2000,506,0,2B,2B303,San-Giuliano,NaN,NC82G25,2000-01-01 17:41:00,3.0,20000,2000-01-01,17:41:00
42481,2000,2644,0,48,48001,Albaret-le-Comtal,test (a supprimer),KD22A2,2000-01-01 01:01:00,NaN,1000,2000-01-01,01:01:00